# This file was generated by GoReleaser. DO NOT EDIT.
cask "angry-bear" do
  version "0.13.1"

  on_macos do
    on_intel do
      sha256 "1d5a6c77c38fcfe0623645a419a6d931e251ee2930a53f473f3ec70711f2e6ff"
      url "https://github.com/bluebear-io/homebrew-angry-bear/releases/download/v#{version}/angry-bear_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0298fb2091f3c9c76dd9cebcecb026dd912670743636d7b561162b1f8e18febc"
      url "https://github.com/bluebear-io/homebrew-angry-bear/releases/download/v#{version}/angry-bear_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3cf4c3eca866a10a442b64636e374308f14c27cf0a2c46774ef8c5c543ba7081"
      url "https://github.com/bluebear-io/homebrew-angry-bear/releases/download/v#{version}/angry-bear_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c2ebae1fcc5e922c3aae2679dca37cf59899d0cbaa36bc893b3fce8336e2e8e"
      url "https://github.com/bluebear-io/homebrew-angry-bear/releases/download/v#{version}/angry-bear_#{version}_linux_arm64.tar.gz"
    end
  end

  name "angry-bear"
  desc "Enforce skill-loading requirements for AI coding agents"
  homepage "https://github.com/bluebear-io/angry-bear"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "angry-bear"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/angry-bear"]
    end
  end

  # No zap stanza required

end
